### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by kober32** [wultra/mtoken-sdk-android#15]
- split README into documentation
- write an example for `LocalOperation`
- add logging level section

**Comment by petrdvorak** [comment]
- Add a separate section for localization.
- Show how to set the operations listener in the periodic polling section.
- Fix inconsistent name in `onQROperationScanned` method (`payload` vs. `scannedCode`).
- Fix occasional extra space in method parameters (after `object`) that are incorrectly rendered on developer portal:
    `operationsService.getOperations(object : IGetOperationListener {`
- Add a reference table of error codes that can occur in the SDK (or link to the code with the enum).
- Fix tabs vs. spaces issue in the code samples.
